id: mago
version:
  source: mago
install-candidates:
  windows-amd64:
    - mago.exe
    - bin/mago.exe
  linux-amd64:
    - mago
    - bin/mago
dispatch-commands:
  - mago
download:
  github:
    owner: carthage-software
    repo: mago
  assets:
    windows-amd64:
      filename: mago-{version}-x86_64-pc-windows-msvc.zip
      url: https://github.com/carthage-software/mago/releases/download/{tag}/mago-{version}-x86_64-pc-windows-msvc.zip
      checksum-algorithm: sha256
      archive-format: zip
    linux-amd64:
      filename: mago-{version}-x86_64-unknown-linux-gnu.tar.gz
      url: https://github.com/carthage-software/mago/releases/download/{tag}/mago-{version}-x86_64-unknown-linux-gnu.tar.gz
      checksum-algorithm: sha256
      archive-format: tar.gz
