id: mailpit
install-candidates:
  windows-amd64:
    - mailpit.exe
    - bin/mailpit.exe
  linux-amd64:
    - mailpit
    - bin/mailpit
dispatch-commands:
  - mailpit
logs:
  info:
    - mailpit.log
download:
  github:
    owner: axllent
    repo: mailpit
    tag-prefix: v
  assets:
    windows-amd64:
      filename: mailpit-{version}-windows-amd64.zip
      source-filename: mailpit-windows-amd64.zip
      url: https://github.com/axllent/mailpit/releases/download/{tag}/mailpit-windows-amd64.zip
      checksum-algorithm: sha256
      archive-format: zip
    linux-amd64:
      filename: mailpit-{version}-linux-amd64.tar.gz
      source-filename: mailpit-linux-amd64.tar.gz
      url: https://github.com/axllent/mailpit/releases/download/{tag}/mailpit-linux-amd64.tar.gz
      checksum-algorithm: sha256
      archive-format: tar.gz
