id: mariadb
logs:
  all:
    - run/db/{env}.log
install-candidates:
  windows-amd64:
    - bin/mariadb.cmd
    - bin/mariadb.bat
    - bin/mariadb.exe
    - bin/mysql.cmd
    - bin/mysql.bat
    - bin/mysql.exe
    - mariadb.cmd
    - mariadb.bat
    - mariadb.exe
    - mysql.cmd
    - mysql.bat
    - mysql.exe
  linux-amd64:
    - bin/mariadb
    - bin/mysql
    - mariadb
    - mysql
dispatch-commands:
  - mariadb
download:
  assets:
    windows-amd64:
      filename: mariadb-{version}-winx64.zip
      url: https://archive.mariadb.org/mariadb-{version}/winx64-packages/mariadb-{version}-winx64.zip
      checksum-url: https://archive.mariadb.org/mariadb-{version}/winx64-packages/sha256sums.txt
      checksum-algorithm: sha256
      archive-format: zip
    linux-amd64:
      filename: mariadb-{version}-linux-systemd-x86_64.tar.gz
      url: https://archive.mariadb.org/mariadb-{version}/bintar-linux-systemd-x86_64/mariadb-{version}-linux-systemd-x86_64.tar.gz
      checksum-url: https://archive.mariadb.org/mariadb-{version}/bintar-linux-systemd-x86_64/sha256sums.txt
      checksum-algorithm: sha256
      archive-format: tar.gz
