id: mysql
install-candidates:
  windows-amd64:
    - bin/mysql.cmd
    - bin/mysql.bat
    - bin/mysql.exe
    - mysql.cmd
    - mysql.bat
    - mysql.exe
  linux-amd64:
    - bin/mysql
    - mysql
dispatch-commands:
  - mysql
logs:
  error:
    - server.log
download:
  assets:
    windows-amd64:
      filename: mysql-{version}-winx64.zip
      url: https://cdn.mysql.com/Downloads/MySQL-{major_minor}/mysql-{version}-winx64.zip
      checksum-url: https://cdn.mysql.com/Downloads/MySQL-{major_minor}/mysql-{version}-winx64.zip.md5
      checksum-algorithm: md5
      archive-format: zip
    linux-amd64:
      filename: mysql-{version}-linux-glibc2.17-x86_64.tar.xz
      url: https://cdn.mysql.com/Downloads/MySQL-{major_minor}/mysql-{version}-linux-glibc2.17-x86_64.tar.xz
      checksum-url: https://cdn.mysql.com/Downloads/MySQL-{major_minor}/mysql-{version}-linux-glibc2.17-x86_64.tar.xz.md5
      checksum-algorithm: md5
      archive-format: tar.xz
