id: nginx
logs:
  all:
    - run/serve/{env}/logs/error.log
    - run/serve/{env}/logs/access.log
    - run/serve/{env}/serve.log
install-candidates:
  windows-amd64:
    - nginx.exe
    - sbin/nginx.exe
  linux-amd64:
    - sbin/nginx
    - nginx
dispatch-commands:
  - nginx
download:
  assets:
    windows-amd64:
      filename: nginx-{version}.zip
      url: https://nginx.org/download/nginx-{version}.zip
      archive-format: zip
