id: nginx
install-candidates:
  windows-amd64:
    - nginx.exe
    - sbin/nginx.exe
  linux-amd64:
    - sbin/nginx
    - nginx
dispatch-commands:
  - nginx
logs:
  info:
    - logs/access.log
  error:
    - logs/error.log
  debug:
    - serve.log
    - php.log
download:
  assets:
    windows-amd64:
      filename: nginx-{version}.zip
      url: https://nginx.org/download/nginx-{version}.zip
      archive-format: zip
