id: nodejs
version:
  source: nodejs
install-candidates:
  windows-amd64:
    - node.exe
    - bin/node.exe
  linux-amd64:
    - bin/node
    - node
dispatch-commands:
  - node
  - npm
  - npx
cleanup-commands:
  - node
  - npm
  - npx
  - nodejs
active-commands:
  - node
  - npm
  - npx
dispatch-candidates:
  node:
    windows-amd64:
      - node.cmd
      - node.exe
      - bin/node.cmd
      - bin/node.exe
    linux-amd64:
      - bin/node
      - node
  npm:
    windows-amd64:
      - npm.cmd
      - npm
      - bin/npm.cmd
      - bin/npm
    linux-amd64:
      - bin/npm
      - npm
  npx:
    windows-amd64:
      - npx.cmd
      - npx
      - bin/npx.cmd
      - bin/npx
    linux-amd64:
      - bin/npx
      - npx
download:
  assets:
    windows-amd64:
      filename: node-v{version}-win-x64.zip
      url: https://nodejs.org/dist/v{version}/node-v{version}-win-x64.zip
      checksum-url: https://nodejs.org/dist/v{version}/SHASUMS256.txt
      checksum-algorithm: sha256
      archive-format: zip
    linux-amd64:
      filename: node-v{version}-linux-x64.tar.xz
      url: https://nodejs.org/dist/v{version}/node-v{version}-linux-x64.tar.xz
      checksum-url: https://nodejs.org/dist/v{version}/SHASUMS256.txt
      checksum-algorithm: sha256
      archive-format: tar.xz
