id: php
logs:
  all:
    - run/serve/{env}/php.log
    - run/serve/{env}/serve.log
install-candidates:
  windows-amd64:
    - bin/php.exe
    - bin/php.cmd
    - bin/php.bat
    - php.exe
    - php.cmd
    - php.bat
  linux-amd64:
    - bin/php
    - php
dispatch-commands:
  - php
