id: phpmyadmin
logs:
  all:
    - run/phpmyadmin/{env}/serve.log
install-candidates:
  all:
    - index.php
download:
  assets:
    all:
      filename: phpMyAdmin-{version}-all-languages.zip
      url: https://files.phpmyadmin.net/phpMyAdmin/{version}/phpMyAdmin-{version}-all-languages.zip
      checksum-url: https://files.phpmyadmin.net/phpMyAdmin/{version}/phpMyAdmin-{version}-all-languages.zip.sha256
      checksum-algorithm: sha256
      archive-format: zip
