id: phpmyadmin
install-candidates:
  all:
    - index.php
logs:
  info:
    - run/phpmyadmin/{environment}/logs/access.log
  error:
    - run/phpmyadmin/{environment}/logs/error.log
  debug:
    - run/phpmyadmin/{environment}/serve.log
    - run/phpmyadmin/{environment}/php.log
download:
  assets:
    all:
      filename: phpMyAdmin-{version}-all-languages.zip
      url: https://files.phpmyadmin.net/phpMyAdmin/{version}/phpMyAdmin-{version}-all-languages.zip
      checksum-url: https://files.phpmyadmin.net/phpMyAdmin/{version}/phpMyAdmin-{version}-all-languages.zip.sha256
      checksum-algorithm: sha256
      archive-format: zip
