id: sqlite
php-extensions:
  - pdo_sqlite
  - sqlite3
install-candidates:
  windows-amd64:
    - sqlite3.cmd
    - sqlite3.bat
    - sqlite3.exe
    - bin/sqlite3.cmd
    - bin/sqlite3.bat
    - bin/sqlite3.exe
  linux-amd64:
    - sqlite3
    - bin/sqlite3
dispatch-commands:
  - sqlite3
download:
  assets:
    windows-amd64:
      filename: sqlite-tools-win-x64-{sqlite_numeric}.zip
      url: https://www.sqlite.org/{sqlite_relative_url}
      checksum-algorithm: sha3-256
      archive-format: zip
    linux-amd64:
      filename: sqlite-tools-linux-x64-{sqlite_numeric}.zip
      url: https://www.sqlite.org/{sqlite_relative_url}
      checksum-algorithm: sha3-256
      archive-format: zip
