package tools

import (
	"bytes"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"unicode/utf16"

	"polka/config"
)

const (
	phpWindowsReleaseURL = "https://windows.php.net/downloads/releases/releases.json"
	phpWindowsBaseURL    = "https://windows.php.net/downloads/releases"
	phpCABundlePath      = "extras/ssl/cacert.pem"
	phpOpenSSLConfigPath = "extras/ssl/openssl.cnf"

	// phpHerdLiteLinuxPath is the herd-lite path segment holding the Linux
	// binaries, which are published per architecture and PHP series.
	phpHerdLiteLinuxPath = "herd-lite/linux"
	// phpHerdLiteFileName and phpHerdLiteInstallPath keep the cached payload
	// and its installed copy aligned with the php install candidates.
	phpHerdLiteFileName    = "php"
	phpHerdLiteInstallPath = "bin/php"
)

// phpHerdLiteBaseURL hosts the standalone PHP binaries that Laravel publishes
// for herd-lite (the runtime behind the php.new installer). It is a variable so
// tests can point the downloader at a local server.
var phpHerdLiteBaseURL = "https://download.herdphp.com"

// elfMagic identifies a Linux executable. herd-lite publishes no checksum
// sidecar, so the download is rejected when the payload is not an ELF binary
// to keep a CDN error page from being cached as a PHP runtime.
var elfMagic = []byte{0x7f, 'E', 'L', 'F'}

var generatedOpenSSLConfig = []byte(strings.Join([]string{
	"# Generated by Polka. Re-run polka install to recreate this file.",
	"HOME = .",
	"",
	"[req]",
	"distinguished_name = req_distinguished_name",
	"",
	"[req_distinguished_name]",
	"",
}, "\n"))

var systemCABundleCandidates = []string{
	"/etc/ssl/certs/ca-certificates.crt",
	"/etc/pki/tls/certs/ca-bundle.crt",
	"/etc/ssl/ca-bundle.pem",
	"/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem",
	"/etc/ssl/cert.pem",
}

type phpWindowsReleaseIndex map[string]phpWindowsRelease

type phpWindowsRelease struct {
	Version  string
	Variants map[string]phpWindowsVariant
}

type phpWindowsVariant struct {
	Zip phpWindowsAsset `json:"zip"`
}

type phpWindowsAsset struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

func phpPlugin() Plugin {
	return phpRuntimePlugin(PHP, false)
}

func phpZTSPlugin() Plugin {
	return phpRuntimePlugin(PHPZTS, true)
}

func phpRuntimePlugin(tool string, threadSafe bool) Plugin {
	return newManifestPlugin(tool, pluginHooks{
		validate: func(environment config.Environment) error {
			if strings.TrimSpace(environment.PHPVersion) != "" && strings.TrimSpace(environment.PHPZTSVersion) != "" {
				return fmt.Errorf("php and php-zts versions are mutually exclusive")
			}
			if version := strings.TrimSpace(pluginPHPVersion(tool, environment)); version != "" {
				if err := validateVersion(tool, version); err != nil {
					return err
				}
			}
			if err := validateOPcachePreset(environment.OPcachePreset); err != nil {
				return err
			}
			for name, value := range environment.OPcacheConfig {
				if err := validateOPcacheDirective(name, value); err != nil {
					return err
				}
			}
			if err := config.ValidatePHPMemoryLimit(environment.MemoryLimit); err != nil {
				return err
			}
			for pkg, version := range environment.PIEExtensions {
				if err := config.ValidatePIEExtensionPackage(pkg); err != nil {
					return err
				}
				if err := config.ValidatePIEExtensionVersion(pkg, version); err != nil {
					return err
				}
			}
			for pkg, extension := range environment.PECLExtensions {
				if err := config.ValidatePECLExtensionPackage(pkg); err != nil {
					return err
				}
				if err := config.ValidatePECLExtensionVersion(pkg, extension.Version); err != nil {
					return err
				}
				for piePackage := range environment.PIEExtensions {
					if PIEExtensionModuleName(piePackage) == strings.ToLower(strings.TrimSpace(pkg)) {
						return fmt.Errorf("PHP module %s is configured through both recommended PIE package %s and legacy PECL", pkg, piePackage)
					}
				}
			}

			return nil
		},
		download: func(ctx DownloadContext) error {
			return downloadPHP(ctx.Client, ctx.CacheDir, tool, ctx.Version, threadSafe)
		},
		postInstall: func(ctx InstallContext) error {
			return SyncInstalledPHPRuntimeConfig(ctx.EnvsDir, ctx.Result.Tool, ctx.Result.Version, ctx.Environment)
		},
	})
}

// SyncInstalledPHPRuntimeConfig regenerates the php.ini and supporting
// OpenSSL/CA-bundle assets for an installed PHP runtime from the effective
// environment config. An empty effective config skips the write: fresh
// installs stay ini-less. Use ResyncInstalledPHPRuntimeConfig after config
// changes that may shrink to empty.
func SyncInstalledPHPRuntimeConfig(envsDir, tool, version string, environment config.Environment) error {
	return syncInstalledPHPRuntimeConfig(envsDir, tool, version, environment, false)
}

// ResyncInstalledPHPRuntimeConfig rewrites the generated php.ini even when
// the effective config is empty so removed extensions and directives
// disappear from a previously generated file.
func ResyncInstalledPHPRuntimeConfig(envsDir, tool, version string, environment config.Environment) error {
	return syncInstalledPHPRuntimeConfig(envsDir, tool, version, environment, true)
}

func syncInstalledPHPRuntimeConfig(envsDir, tool, version string, environment config.Environment, force bool) error {
	if _, err := ensureInstalledPHPOpenSSLConfig(envsDir, tool, version); err != nil {
		return err
	}

	phpConfig := EffectivePHPConfigForInstall(environment)
	if phpConfigNeedsCABundle(phpConfig) {
		caBundlePath, err := ensureInstalledPHPCABundle(envsDir, tool, version)
		if err != nil {
			return err
		}
		phpConfig.CABundlePath = caBundlePath
	}
	if phpConfig.IsZero() && !force {
		return nil
	}

	return writeInstalledPHPConfigForTool(envsDir, tool, version, phpConfig)
}

func pluginPHPVersion(tool string, environment config.Environment) string {
	if tool == PHPZTS {
		return environment.PHPZTSVersion
	}

	return environment.PHPVersion
}

func phpConfigNeedsCABundle(config PHPInstallConfig) bool {
	for name, enabled := range config.Extensions {
		if !enabled {
			continue
		}
		switch normalizePHPModuleName(name) {
		case "curl", "openssl":
			return true
		}
	}

	return false
}

func ensureInstalledPHPCABundle(envsDir, tool, version string) (string, error) {
	caBundlePath := installedPHPCABundlePath(envsDir, tool, version)
	exists, err := regularPHPFileExists(caBundlePath)
	if err != nil {
		return "", fmt.Errorf("stat php ca bundle %s: %w", caBundlePath, err)
	}
	if exists {
		return caBundlePath, nil
	}

	if runtime.GOOS == "windows" {
		if err := writeWindowsSystemCABundle(caBundlePath); err != nil {
			return "", err
		}
		return caBundlePath, nil
	}

	systemPath, err := findSystemCABundle()
	if err != nil {
		return "", err
	}

	return systemPath, nil
}

func installedPHPCABundlePath(envsDir, tool, version string) string {
	return filepath.Join(envsDir, tool, version, filepath.FromSlash(phpCABundlePath))
}

func ensureInstalledPHPOpenSSLConfig(envsDir, tool, version string) (string, error) {
	return ensureInstalledPHPOpenSSLConfigAt(filepath.Join(envsDir, tool, version))
}

func ensureInstalledPHPOpenSSLConfigAt(installDir string) (string, error) {
	configPath := filepath.Join(installDir, filepath.FromSlash(phpOpenSSLConfigPath))
	exists, err := regularPHPFileExists(configPath)
	if err != nil {
		return "", fmt.Errorf("stat php openssl config %s: %w", configPath, err)
	}
	if exists {
		return configPath, nil
	}

	if err := os.MkdirAll(filepath.Dir(configPath), 0o755); err != nil {
		return "", fmt.Errorf("create php openssl config directory: %w", err)
	}
	if err := os.WriteFile(configPath, generatedOpenSSLConfig, 0o644); err != nil {
		return "", fmt.Errorf("write php openssl config: %w", err)
	}

	return configPath, nil
}

func installedPHPOpenSSLConfigPath(envsDir, tool, version string) string {
	return filepath.Join(envsDir, tool, version, filepath.FromSlash(phpOpenSSLConfigPath))
}

func findSystemCABundle() (string, error) {
	for _, path := range systemCABundleCandidates {
		exists, err := regularPHPFileExists(path)
		if err != nil {
			return "", fmt.Errorf("stat system ca bundle %s: %w", path, err)
		}
		if exists {
			return path, nil
		}
	}

	return "", fmt.Errorf("no system ca bundle found for generated PHP OpenSSL/cURL config")
}

func regularPHPFileExists(path string) (bool, error) {
	info, err := os.Stat(path)
	if err == nil {
		return !info.IsDir(), nil
	}
	if os.IsNotExist(err) {
		return false, nil
	}

	return false, err
}

func writeWindowsSystemCABundle(targetPath string) error {
	data, err := exportWindowsSystemCABundle()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
		return fmt.Errorf("create php ca bundle directory: %w", err)
	}
	if err := os.WriteFile(targetPath, data, 0o644); err != nil {
		return fmt.Errorf("write php ca bundle: %w", err)
	}

	return nil
}

func exportWindowsSystemCABundle() ([]byte, error) {
	script := strings.Join([]string{
		"$ErrorActionPreference = 'Stop'",
		"$seen = New-Object 'System.Collections.Generic.HashSet[string]'",
		"foreach ($location in @('CurrentUser', 'LocalMachine')) {",
		"  $store = New-Object System.Security.Cryptography.X509Certificates.X509Store('Root', $location)",
		"  $store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly)",
		"  try {",
		"    foreach ($cert in $store.Certificates) {",
		"      if ([string]::IsNullOrWhiteSpace($cert.Thumbprint) -or -not $seen.Add($cert.Thumbprint)) { continue }",
		"      '-----BEGIN CERTIFICATE-----'",
		"      [Convert]::ToBase64String($cert.RawData, [Base64FormattingOptions]::InsertLineBreaks)",
		"      '-----END CERTIFICATE-----'",
		"      ''",
		"    }",
		"  } finally {",
		"    $store.Close()",
		"  }",
		"}",
	}, "\n")

	command := exec.Command("powershell.exe", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-EncodedCommand", powershellEncodedCommand(script))
	var stderr bytes.Buffer
	command.Stderr = &stderr
	output, err := command.Output()
	if err != nil {
		detail := strings.TrimSpace(stderr.String())
		if detail != "" {
			return nil, fmt.Errorf("export windows root certificates: %w: %s", err, detail)
		}
		return nil, fmt.Errorf("export windows root certificates: %w", err)
	}
	if !bytes.Contains(output, []byte("-----BEGIN CERTIFICATE-----")) {
		return nil, fmt.Errorf("export windows root certificates: no certificates were exported")
	}

	return output, nil
}

func powershellEncodedCommand(script string) string {
	encodedRunes := utf16.Encode([]rune(script))
	data := make([]byte, len(encodedRunes)*2)
	for index, encodedRune := range encodedRunes {
		binary.LittleEndian.PutUint16(data[index*2:], encodedRune)
	}

	return base64.StdEncoding.EncodeToString(data)
}

func validateOPcachePreset(preset string) error {
	switch config.NormalizeOPcachePreset(preset) {
	case "", config.OPcachePresetDev, config.OPcachePresetProduction:
		return nil
	default:
		return fmt.Errorf("unsupported opcache-preset %q: use none, dev, or production", preset)
	}
}

// downloadPHP caches a PHP runtime for the current platform. Windows uses the
// official windows.php.net release index; Linux uses the herd-lite standalone
// binaries because php.net publishes no prebuilt Linux runtime.
func downloadPHP(client *http.Client, cacheDir, tool, version string, threadSafe bool) error {
	switch runtime.GOOS {
	case "windows":
		return downloadWindowsPHP(client, cacheDir, tool, version, threadSafe)
	case "linux":
		return downloadLinuxPHP(client, cacheDir, tool, version, threadSafe, runtime.GOARCH)
	default:
		return fmt.Errorf("automatic php download is only implemented on Windows and Linux")
	}
}

// downloadLinuxPHP caches a herd-lite standalone PHP binary. herd-lite
// publishes a single non-thread-safe build per PHP series without a checksum
// sidecar, so the cache records the SHA-256 it computes over the download.
// The requested patch level is not part of the URL: the series build is
// whatever patch release herd-lite currently ships, matching how the Windows
// release index resolves a series to its latest patch.
func downloadLinuxPHP(client *http.Client, cacheDir, tool, version string, threadSafe bool, goarch string) error {
	if threadSafe {
		return fmt.Errorf("automatic %s download is not available on Linux: herd-lite publishes non-thread-safe PHP builds only", tool)
	}

	architecture, err := phpHerdLiteArchitecture(goarch)
	if err != nil {
		return err
	}
	series := phpSeries(version)
	if series == "" {
		return fmt.Errorf("php version cannot be empty")
	}

	if err := os.MkdirAll(filepath.Join(cacheDir, tool), 0o755); err != nil {
		return fmt.Errorf("create php cache dir: %w", err)
	}

	stagingDir, err := os.MkdirTemp(filepath.Join(cacheDir, tool), version+"-tmp-")
	if err != nil {
		return fmt.Errorf("create php staging dir: %w", err)
	}
	defer os.RemoveAll(stagingDir)

	binaryURL := fmt.Sprintf("%s/%s/%s/%s/%s", strings.TrimRight(phpHerdLiteBaseURL, "/"), phpHerdLiteLinuxPath, architecture, series, phpHerdLiteFileName)
	binaryPath := filepath.Join(stagingDir, phpHerdLiteFileName)
	if err := downloadFile(client, binaryURL, binaryPath); err != nil {
		return fmt.Errorf("php %s is not available from herd-lite for linux/%s: %w", series, architecture, err)
	}
	if err := verifyELFBinary(binaryPath); err != nil {
		return fmt.Errorf("download %s: %w", binaryURL, err)
	}

	_, err = cacheFilePayload(cacheDir, tool, version, version, phpHerdLiteFileName, binaryURL, phpHerdLiteInstallPath, checksumAlgorithmNone, "", binaryPath)
	return err
}

// phpHerdLiteArchitecture maps a Go architecture onto the herd-lite path
// segment for the matching Linux binary.
func phpHerdLiteArchitecture(goarch string) (string, error) {
	switch strings.TrimSpace(goarch) {
	case "amd64":
		return "x64", nil
	case "arm64":
		return "arm64", nil
	default:
		return "", fmt.Errorf("automatic php download is not available for linux/%s", goarch)
	}
}

// verifyELFBinary reports whether a downloaded file starts with the ELF magic
// number, guarding an unsigned download against non-binary error responses.
func verifyELFBinary(path string) error {
	file, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("open downloaded php binary %s: %w", path, err)
	}
	defer file.Close()

	header := make([]byte, len(elfMagic))
	if _, err := io.ReadFull(file, header); err != nil {
		return fmt.Errorf("read downloaded php binary %s: %w", path, err)
	}
	if !bytes.Equal(header, elfMagic) {
		return fmt.Errorf("downloaded php binary %s is not a Linux executable", path)
	}

	return nil
}

func downloadWindowsPHP(client *http.Client, cacheDir, tool, version string, threadSafe bool) error {
	if err := os.MkdirAll(filepath.Join(cacheDir, tool), 0o755); err != nil {
		return fmt.Errorf("create php cache dir: %w", err)
	}

	index, err := fetchPHPWindowsReleaseIndex(client)
	if err != nil {
		return err
	}

	series := phpSeries(version)
	release, ok := index[series]
	if !ok {
		return fmt.Errorf("php version %q is not available in the Windows release index", version)
	}

	asset, err := selectPHPWindowsAsset(release, threadSafe)
	if err != nil {
		return err
	}

	stagingDir, err := os.MkdirTemp(filepath.Join(cacheDir, tool), version+"-tmp-")
	if err != nil {
		return fmt.Errorf("create php staging dir: %w", err)
	}
	defer os.RemoveAll(stagingDir)

	archivePath := filepath.Join(stagingDir, filepath.Base(asset.Path))
	archiveURL := fmt.Sprintf("%s/%s", phpWindowsBaseURL, asset.Path)
	if err := downloadFile(client, archiveURL, archivePath); err != nil {
		return err
	}
	if err := verifyChecksum(asset.SHA256, archivePath); err != nil {
		return err
	}

	_, err = cacheArchivePayload(cacheDir, tool, version, release.Version, downloadAsset{
		FileName:          filepath.Base(asset.Path),
		URL:               archiveURL,
		Checksum:          asset.SHA256,
		ChecksumAlgorithm: checksumAlgorithmSHA256,
		ArchiveFormat:     archiveFormatZip,
	}, archivePath)
	return err
}

func fetchPHPWindowsReleaseIndex(client *http.Client) (phpWindowsReleaseIndex, error) {
	response, err := client.Get(phpWindowsReleaseURL)
	if err != nil {
		return nil, fmt.Errorf("download php release index: %w", err)
	}
	defer response.Body.Close()

	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("download php release index: unexpected status %s", response.Status)
	}

	var index phpWindowsReleaseIndex
	if err := json.NewDecoder(response.Body).Decode(&index); err != nil {
		return nil, fmt.Errorf("decode php release index: %w", err)
	}

	return index, nil
}

func (r *phpWindowsRelease) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	r.Variants = map[string]phpWindowsVariant{}
	for key, value := range raw {
		switch key {
		case "version":
			if err := json.Unmarshal(value, &r.Version); err != nil {
				return err
			}
		case "source", "test_pack":
			continue
		default:
			var variant phpWindowsVariant
			if err := json.Unmarshal(value, &variant); err != nil {
				continue
			}
			if variant.Zip.Path != "" {
				r.Variants[key] = variant
			}
		}
	}

	return nil
}

func selectPHPWindowsAsset(release phpWindowsRelease, threadSafe bool) (phpWindowsAsset, error) {
	architecture := "x64"
	if runtime.GOARCH == "386" {
		architecture = "x86"
	}

	flavor := "nts"
	if threadSafe {
		flavor = "ts"
	}
	preferences := []string{
		flavor + "-vs17-" + architecture,
		flavor + "-vs16-" + architecture,
		flavor + "-vc15-" + architecture,
	}

	for _, key := range preferences {
		if variant, ok := release.Variants[key]; ok && variant.Zip.Path != "" {
			return variant.Zip, nil
		}
	}

	return phpWindowsAsset{}, fmt.Errorf("no compatible Windows PHP %s binary found for %s on %s", strings.ToUpper(flavor), release.Version, architecture)
}

func phpSeries(version string) string {
	parts := strings.Split(strings.TrimSpace(version), ".")
	if len(parts) >= 2 {
		return parts[0] + "." + parts[1]
	}

	return strings.TrimSpace(version)
}
