package tools

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"polka/config"
)

var composerDefaultExtensions = []string{"openssl", "zip"}

func EffectivePHPExtensionsForInstall(environment config.Environment) map[string]bool {
	if environment.ComposerVersion == "" {
		return environment.PHPExtensions
	}

	effective := make(map[string]bool, len(environment.PHPExtensions)+len(composerDefaultExtensions))
	for name, enabled := range environment.PHPExtensions {
		effective[name] = enabled
	}
	for _, name := range composerDefaultExtensions {
		if _, ok := effective[name]; !ok {
			effective[name] = true
		}
	}

	return effective
}

func configureInstalledPHPExtensions(envsDir, version string, extensions map[string]bool) error {
	if len(extensions) == 0 {
		return nil
	}

	phpPath, err := resolveInstalledTool(NewDefaultRegistry(), envsDir, PHP, version)
	if err != nil {
		return err
	}

	phpDir := filepath.Dir(phpPath)
	extensionDir, err := filepath.Rel(phpDir, filepath.Join(envsDir, PHP, version, "ext"))
	if err != nil {
		extensionDir = filepath.Join(envsDir, PHP, version, "ext")
	}

	configData, err := renderPHPExtensionConfig(filepath.ToSlash(extensionDir), extensions)
	if err != nil {
		return err
	}

	phpIniPath := filepath.Join(phpDir, "php.ini")
	if err := os.WriteFile(phpIniPath, configData, 0o644); err != nil {
		return fmt.Errorf("write php extension config: %w", err)
	}

	return nil
}

func renderPHPExtensionConfig(extensionDir string, extensions map[string]bool) ([]byte, error) {
	names := make([]string, 0, len(extensions))
	for name := range extensions {
		if err := validatePHPExtensionName(name); err != nil {
			return nil, err
		}

		names = append(names, name)
	}
	sort.Strings(names)

	var builder strings.Builder
	builder.WriteString("; Generated by Polka. Re-run polka install after editing php-extensions.\n")
	builder.WriteString("[PHP]\n")
	builder.WriteString("extension_dir=\"")
	builder.WriteString(extensionDir)
	builder.WriteString("\"\n")
	for _, name := range names {
		if extensions[name] {
			builder.WriteString("extension=")
		} else {
			builder.WriteString(";extension=")
		}
		builder.WriteString(name)
		builder.WriteByte('\n')
	}

	return []byte(builder.String()), nil
}

func validatePHPExtensionName(name string) error {
	trimmed := strings.TrimSpace(name)
	if trimmed == "" {
		return fmt.Errorf("php extension name cannot be empty")
	}
	if !validName.MatchString(trimmed) {
		return fmt.Errorf("invalid php extension name %q: use letters, numbers, dots, dashes, or underscores", name)
	}

	return nil
}
