package tools

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"polka/config"
)

const (
	phpMyAdminConfigFileName = "config.inc.php"
	phpMyAdminTempDirectory  = "tmp"
	phpMyAdminDatabaseHost   = "127.0.0.1"
	phpMyAdminDefaultDBPort  = 3306
	phpMyAdminStorageDBName  = "phpmyadmin"
)

var phpMyAdminStorageTables = []struct {
	key  string
	name string
}{
	{"bookmarktable", "pma__bookmark"},
	{"relation", "pma__relation"},
	{"table_info", "pma__table_info"},
	{"table_coords", "pma__table_coords"},
	{"pdf_pages", "pma__pdf_pages"},
	{"column_info", "pma__column_info"},
	{"history", "pma__history"},
	{"table_uiprefs", "pma__table_uiprefs"},
	{"tracking", "pma__tracking"},
	{"userconfig", "pma__userconfig"},
	{"recent", "pma__recent"},
	{"favorite", "pma__favorite"},
	{"users", "pma__users"},
	{"usergroups", "pma__usergroups"},
	{"navigationhiding", "pma__navigationhiding"},
	{"savedsearches", "pma__savedsearches"},
	{"central_columns", "pma__central_columns"},
	{"designer_settings", "pma__designer_settings"},
	{"export_templates", "pma__export_templates"},
}

func configureInstalledPHPMyAdmin(ctx InstallContext) error {
	installDir := filepath.Dir(ctx.Result.TargetPath)
	if strings.TrimSpace(installDir) == "." || strings.TrimSpace(installDir) == "" {
		installDir = filepath.Join(ctx.EnvsDir, PHPMyAdmin, ctx.Result.Version)
	}

	secret, err := generatePHPMyAdminBlowfishSecret()
	if err != nil {
		return err
	}
	configData := renderPHPMyAdminConfig(secret, ctx.Environment.Database)
	configPath := filepath.Join(installDir, phpMyAdminConfigFileName)
	if err := os.WriteFile(configPath, configData, 0o644); err != nil {
		return fmt.Errorf("write phpmyadmin config: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(installDir, phpMyAdminTempDirectory), 0o755); err != nil {
		return fmt.Errorf("create phpmyadmin temp directory: %w", err)
	}

	return nil
}

func generatePHPMyAdminBlowfishSecret() (string, error) {
	buffer := make([]byte, 24)
	if _, err := rand.Read(buffer); err != nil {
		return "", fmt.Errorf("generate phpmyadmin blowfish secret: %w", err)
	}

	return base64.RawStdEncoding.EncodeToString(buffer), nil
}

func renderPHPMyAdminConfig(blowfishSecret string, database *config.DatabaseConfig) []byte {
	port := phpMyAdminDefaultDBPort
	enableStorage := false
	if database != nil && strings.TrimSpace(database.Engine) != "" {
		enableStorage = true
		if database.Port != 0 {
			port = database.Port
		}
	}

	var builder strings.Builder
	builder.WriteString("<?php\n")
	builder.WriteString("declare(strict_types=1);\n\n")
	builder.WriteString("/**\n")
	builder.WriteString(" * Generated by Polka. Re-run polka install after editing phpMyAdmin or database settings.\n")
	builder.WriteString(" */\n")
	builder.WriteString("$cfg['blowfish_secret'] = ")
	builder.WriteString(phpSingleQuotedString(blowfishSecret))
	builder.WriteString(";\n\n")
	builder.WriteString("$i = 0;\n")
	builder.WriteString("$i++;\n")
	builder.WriteString("$cfg['Servers'][$i]['auth_type'] = 'cookie';\n")
	builder.WriteString("$cfg['Servers'][$i]['host'] = ")
	builder.WriteString(phpSingleQuotedString(phpMyAdminDatabaseHost))
	builder.WriteString(";\n")
	builder.WriteString("$cfg['Servers'][$i]['port'] = ")
	builder.WriteString(phpSingleQuotedString(strconv.Itoa(port)))
	builder.WriteString(";\n")
	builder.WriteString("$cfg['Servers'][$i]['compress'] = false;\n")
	builder.WriteString("$cfg['Servers'][$i]['AllowNoPassword'] = false;\n")
	if enableStorage {
		builder.WriteString("$cfg['Servers'][$i]['pmadb'] = ")
		builder.WriteString(phpSingleQuotedString(phpMyAdminStorageDBName))
		builder.WriteString(";\n")
		for _, table := range phpMyAdminStorageTables {
			builder.WriteString("$cfg['Servers'][$i]['")
			builder.WriteString(table.key)
			builder.WriteString("'] = ")
			builder.WriteString(phpSingleQuotedString(table.name))
			builder.WriteString(";\n")
		}
		builder.WriteByte('\n')
	}
	builder.WriteString("$cfg['TempDir'] = __DIR__ . '/tmp';\n")
	builder.WriteString("$cfg['UploadDir'] = '';\n")
	builder.WriteString("$cfg['SaveDir'] = '';\n")

	return []byte(builder.String())
}

func phpSingleQuotedString(value string) string {
	escaped := strings.ReplaceAll(value, "\\", "\\\\")
	escaped = strings.ReplaceAll(escaped, "'", "\\'")
	return "'" + escaped + "'"
}
